### ISSUE TITLE
bot can not get twitch info

### ISSUE THREAD

**Issue by ariaieboy** [Kamiikaze/Sinusbot-Customization#6]
hi i installed the script and i config it and put my client id in the config form 
but after i start the bot its says this message in log 
 DEBUG: No Data returned: undefined
and can not show the title and etc

**Comment by ariaieboy** [comment]
added #7 to fix this problem

worked for me so far

**Comment by Kamiikaze** [comment]
> added #7 to fix this problem
> 
> worked for me so far

Does everything work for you? I don't think so, because in the newer API the data is now on different places than before. Thats why I am rewriting the script. I already started to do it, but I lacked on time. I will look into it tmrw and check your pull request. Thanks! :)

**Comment by ariaieboy** [comment]
> > added #7 to fix this problem
> > worked for me so far
> 
> Does everything work for you? I don't think so, because in the newer API the data is now on different places than before. Thats why I am rewriting the script. I already started to do it, but I lacked on time. I will look into it tmrw and check your pull request. Thanks! :)

with my tests yes its work good 
i didnt change the api to the latest one i just update it to version 5 
according to this page : https://dev.twitch.tv/docs/v5/guides/migration

i just added the "Accept: application/vnd.twitchtv.v5+json" header 
and add a new var for twitch uid 
and change username api call to a uid api call 

u can get uid using username over api but i didnt wanna add that extra request and just added a var for it in config
